# Generated by Django 6.0.5 on 2026-05-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='users/default.jpg', upload_to='users/%Y/%m/%d'),
        ),
    ]
