# Generated by Django 6.0.5 on 2026-05-20 21:48

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
    ]
